#!/usr/bin/env python

import sys
changes_made = False

try:
    with open(f"/usr/applications/{sys.argv[1]}.desktop", "w+") as desktop_file:
        data = desktop_file.readlines()
        if data[5][5:15] == "prime-run":
            print("Application is already set to use nvidia")
        else:
            data[5] = f"Exec=prime-run {data[5][5:]}"
            changes_made = True
except:
    print(f"{sys.argv[1]}: package not found")

if changes_made:
    with open(f"/usr/applications/{sys.argv[1]}.desktop", "w+") as desktop_file:
        data = ''.join(data)
        desktop_file.write(data)
